"""
sentence = "The forward player scored to the goalkeeper because he was good."
snippet = "he was good"
pronoun = "he"
answer_a = "The forward player"
answer_b = "The goalkeeper"
sentence_bis = "The forward player scored to the goalkeeper because he was bad."
snippet_bis = "he was bad"

sentence = "The forward player missed against the goalkeeper because he was good."
snippet = "he was good"
pronoun = "he"
answer_a = "The forward player"
answer_b = "The goalkeeper"
sentence_bis = "The forward player missed against the goalkeeper because he was bad."
snippet_bis = "he was bad"

sentence = "The forward player scored to the goalkeeper although he was good."
snippet = "he was good"
pronoun = "he"
answer_a = "The forward player"
answer_b = "The goalkeeper"
sentence_bis = "The forward player scored to the goalkeeper although he was bad."
snippet_bis = "he was bad"

sentence = "The forward player missed against the goalkeeper although he was good."
snippet = "he was good"
pronoun = "he"
answer_a = "The forward player"
answer_b = "The goalkeeper"
sentence_bis = "The forward player missed against the goalkeeper although he was bad."
snippet_bis = "he was bad"
"""

print("Wrong answer")
